Repository DearGraduate/graduate-be, pull requests merged in 2025-07, with the labels that each got.

#2 🚀 [DEPLOY/#1] CICD 파이프라인 구축
  .github/workflows/workflows.yml
  Dockerfile
  docker-compose.yml
  prometheus.yml
  src/main/resources/application-prod.yml
Labels: 🌏 Deploy

#14 ✨ [FEAT/#7] 로그아웃 로직 추가
  src/main/java/com/example/graduate/domain/user/controller/AuthController.java
  src/main/java/com/example/graduate/domain/user/exception/UserSuccessStatus.java
  src/main/java/com/example/graduate/domain/user/service/UserService.java
Labels: ✨ Feature

#26 🐛 Prod 환경파일 수정
  src/main/resources/application-prod.yml
Labels: 🐛 BugFix

#27 ✨ [FEAT/#25] 초기화면 누적 앨범·축하글 수 조회 구현
  src/main/java/com/example/graduate/domain/album/service/AlbumService.java
  src/main/java/com/example/graduate/domain/letter/service/LetterService.java
  src/main/java/com/example/graduate/domain/project/controller/ProjectController.java
  src/main/java/com/example/graduate/domain/project/dto/response/ProjectResponseDTO.java
  src/main/java/com/example/graduate/domain/project/service/ProjectService.java
  src/main/java/com/example/graduate/global/config/SecurityConfig.java
  src/main/java/com/example/graduate/global/redis/RedisUtil.java
Labels: ✨ Feature

#22 ♻️ [REFACTOR/#18] 카카오 로그인 리다이렉트 방식 수정
  src/main/java/com/example/graduate/domain/user/controller/KakaoOAuthController.java
  src/main/java/com/example/graduate/domain/user/service/KakaoOAuthService.java
Labels: :hammer: Refactor, ✨ Feature
